### PR TITLE
feat: add declaration file to support typescript

### PR DESCRIPTION
**Pull request by SoraYama**
### Requirements

 - [x] Have you viewed your changes locally on the demos page, located on https://github.com/mattboldt/typed.js/blob/master/index.html?

 - [ ] If necessary, have you added a new demo to the index.html list of demos? If it's an improvement or small addition, have you added it to an existing demo on the demos page?

 - [ ] If applicable, have you created a fork of the following JSFiddle with your branch's code and your new feature showcased?

### Description of the Change
Add `index.d.ts` to support typing in typescript.

### Benefits
- Support typescript.
- Coding with autocomplete.
- Get comments and safe-types declared in docs.

### CODE REVIEW

**Comment by SoraYama** [comment]
### Usage
```
import Typed from 'typed.js'
const typedInstance = new Typed('#foo', {
  strings: ['foo', 'bar']
}
...
```

**Comment by inunotaisho26** [comment]
@mattboldt here

**Comment by mattboldt** [comment]
Awesome! Do we need to add anything to the `package.json` for this to work in TypeScript projects? Or will it just detect the `index.d.ts` once released on npm?

**Comment by inunotaisho26** [comment]
@SoraYama @mattboldt `"typings": "index.d.ts",` to be added right below the `main` key-value pair. `"index.d.ts"` also needs to be included a `files` key-value pair.

**Comment by SoraYama** [comment]
@inunotaisho26 oh, according to current [typescript docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html), to import a non-relative module (e.g. import typed.js from `node_modules`), just add a definition file named `typed.d.ts` or `index.d.ts` to the root dir of the module will be fine.

**Pull request merged**
