### PR TITLE
Fix cursor blink animation.

### PR DESCRIPTION
**Pull request by anteprimorac**
### Requirements

 - [x] Have you viewed your changes locally on the demos page, located on https://github.com/mattboldt/typed.js/blob/master/index.html?

 - [x] If necessary, have you added a new demo to the index.html list of demos? If it's an improvement or small addition, have you added it to an existing demo on the demos page?

 - [x] If applicable, have you created a fork of the following JSFiddle with your branch's code and your new feature showcased?
https://jsfiddle.net/anteprimorac/u7h50cy7/2/

### Description of the Change
This pull request fixes cursor blink animation by toggling `blink` class on `.typed-cursor` element.

### CODE REVIEW

**Comment by anteprimorac** [comment]
This PR should fix #291.

**Comment by mattboldt** [comment]
So the main fix here is the usage of `animationIterationCount`? That wasn't working on the linked issue? Also, could you renamed the `.blink` class to something more specific? That's too generic of a name to set globally.

**Comment by anteprimorac** [comment]
Hi @mattboldt ,
yes, changing `animationIterationCount` doesn't reset the animation.
`.blink` is now replaced with `.typed-cursor--blink`.

Do you want this in separate branch?

**Comment by dbkaplun** [comment]
Any progress on this? I can confirm that the issue is related to `animationIterationCount`.

**Comment by anteprimorac** [comment]
Hi @mattboldt, can you merge this PR?

**Pull request merged**
