### PR TITLE
[Update] Callbacks: call all callback functions with context

### PR DESCRIPTION
**Pull request by d-simon**
This allows for runtime modification of options such as typeSpeed.

### CODE REVIEW

**Comment by mattboldt** [comment]
Can I see a jsbin of this being used?

**Comment by elboletaire** [comment]
Using `call` allows us to use `this` inside the callbacks and that `this` will refer to the pageflip object scope instead of the callback scope (where is a bit useless).

**Comment by sash003** [comment]
Thanks! :100:  Look at this http://web4myself.ru/ :)

**Comment by mattboldt** [comment]
added on https://github.com/mattboldt/typed.js/pull/264

**Pull request closed without merging**
