### PR TITLE
New option: onBegin(). A custom event before it begins typing.

### PR DESCRIPTION
**Pull request by seifsg**
### Requirements

 - [X] Have you viewed your changes locally on the demos page, located on https://github.com/mattboldt/typed.js/blob/master/index.html?

 - [X] If necessary, have you added a new demo to the index.html list of demos? If it's an improvement or small addition, have you added it to an existing demo on the demos page?

 - [X] If applicable, have you created a fork of the following JSFiddle with your branch's code and your new feature showcased?

Here is the fiddle: https://jsfiddle.net/seifsg/gknstoff/

### Description of the Change

I was working on my app and I needed to fire an event just right before it begins typing. I didn't find how so I added it the code. Works fine on my app now.

Also, I have added it to the documentation and the demo.

I hope it helps!

### Benefits

New option: onBegin() 
A custom function just before it begins typing

### Issues

No issues yet.

### CODE REVIEW

**Comment by seifsg** [comment]
@mattboldt added the fiddle. Please review, I hope it helps. Thanks a lot.

**Comment by mattboldt** [comment]
Thank you for the addition!

However, it looks like you switched from 2 spaces of indentation to 4 spaces. Could you fix that first?

**Comment by seifsg** [comment]
@mattboldt  Sorry about that. Can you please tell me how can I fix it? I have no idea at the moment about how indentation changed. I'm currently using VSCode and I don't have the 4 spaces issue, it is only showing 2 spaces.

**Comment by mattboldt** [comment]
Just realized it’s in the compiled versions of the source. Must be something up with the gulp config?

**Comment by marabesi** [comment]
@mattboldt

**Comment by marabesi** [comment]
is there any change to get this integrated?

**Comment by mattboldt** [comment]
Moving to https://github.com/mattboldt/typed.js/pull/429 due to conflicts/formatting issues

**Comment by mattboldt** [comment]
Sorry for the delay, this is in the newest release! @marabesi @seifsg 
 https://github.com/mattboldt/typed.js/releases/tag/v2.0.11

**Pull request closed without merging**
