### PR TITLE
Implement bulk backspacing with a flag

### PR DESCRIPTION
**Pull request by crammag**
### Requirements

 - [x] Have you viewed your changes locally on the demos page, located on https://github.com/mattboldt/typed.js/blob/master/index.html?

 - [x] If necessary, have you added a new demo to the index.html list of demos? If it's an improvement or small addition, have you added it to an existing demo on the demos page?

 - [x] **<- (Yes and no, check note below)** If applicable, have you created a fork of the following JSFiddle with your branch's code and your new feature showcased?

I have created it, but I'm not able to make it work with my compilated output, maybe I'm doing something wrong? https://jsfiddle.net/uv3a6fxz/
I had some compatibility issues when building with gulp and node 14, but after downgrading to node 10 LTS it worked, maybe it's because of that :S

### Description of the Change

The change was making the bulk type feature work when backspacing, but as we don't have any marks on the text when you are backspacing (you don't have the ` anymore, because it was stripped from the original text), I had to save some breakpoints that indicate the position where the bulk ends (when backspacing it's the start position) and the length of the bulk (numChars), to be able to reproduce the same behavior.

I have added a flag to enable this behavior because maybe you don't want this by default.

I modified also the bulk type demo (the demo number 6) to make this change more clear, but I can leave it as it was if it's a problem (I changed the backspeed from 0 to 40)

To understand a bit more the motivations of this change, you can check this issue: https://github.com/mattboldt/typed.js/issues/495

### Benefits

It allows you to bulk type in both directions (on type and on backspace), using a flag to enable this mode.

### Issues

I don't think there are any issues created by this feature (and I haven't seen any on the demos page neither), but being under a flag makes it more safe in case I haven't seen something :/

### CODE REVIEW

**Comment by crammag** [comment]
I'm not sure what is failing on the checks, some help would be appreciated.

**Comment by crammag** [comment]
stale = false;

**Comment by mattboldt** [comment]
hey @crammag! sorry for the delayed response. I really appreciate your contribution, I just haven't had a moment to review it. I'll try and get to it soon.

**Comment by crammag** [comment]
Hey @mattboldt, is there any chance to keep this open or something? It has been a while and I don't need this feature anymore, but it could be needed by someone at some point in time (who knows) and being marked as closed and wontfix is not the best for visibility :(

**Comment by mattboldt** [comment]
Reopening! Life's been busy and I haven't revisited this yet, but I'm still interested in the feature

**Comment by linus-jansson** [comment]
:(

**Pull request closed without merging**
