### PR TITLE
Add stop and start function

### LINKED ISSUE #246: Click on input field to type
I have the following input and script:

`<input type="search" name="term" id="term" class="search--input" placeholder="" autocomplete="off">`

```
document.addEventListener("DOMContentLoaded", function(){
    Typed.new(".search--input", {
      strings: ["where ^150do ^150you ^150want ^150to ^150go?", "new ^150york ^150city", "thailand", "france"],
      typeSpeed: 60,
      backSpeed: 50,
      startDelay: 200,
      backDelay: 400,
      loop: true
    });
  });
```

The `loop` is set to `true`. When I click on the input field, I don't want the `Typed` to keep typing, but stop it, so that I can enter my own values to the input field. A callback like on click the input element, then clears the value or stops the typing would be great.

### PR DESCRIPTION
**Pull request by Orlandster98**
fixes #246 #202 #111 

I've added a stop and start function. Here's a plunkr: https://plnkr.co/edit/wF6M9Sd34sP8wdHmE6dK?p=preview

I saw there was an approach before. To make it run we have to work on an object reference. Otherwise the `this` context would be wrong.  Since it's possible to initialize multiple identifiers I have to return an array of all the objects. 

In general, I think it's a good approach to return the references. It gives the user control on the whole behavior after the initialization.

@mattboldt would love to hear your feedback and possible changes. If you like the approach I would really like to export the duplicated code into a function and update the documentation before the merge.

THX!

### CODE REVIEW

**Comment by mattboldt** [comment]
Very cool! A couple things, though:

When stopping & removing text from the DOM, is the intended behavior to pick up where it left off when clicking "start" again? And when the typing is finished, what should "stop and remove" do?

Also, there's a vanilla JS initializer and a jQuery one. I saw you added the `instances` array to `Typed.new` but not the `$.typed()` part.

If you could clear those up that'd be great! And thanks for contributing.

**Comment by Orlandster98** [comment]
@mattboldt I've added the jQuery initializer. Thanks for the hint!

These are very good questions. I'm not sure which is the most wanted behavior. I could add a parameter to the `start` function. `fromBegining: boolean` which starts the typing from the beginning if `true`. 

In my opinion `start` and `stop` should just work while the execution runs. What do you think about it?

**Comment by riverofjanuary** [comment]
Hi all, how do I actually use the stop() function? Is it as simple as

`$("#sidebar_searcher").typed(sidebarSearchOptions);`

To initiate, and 

`$("#sidebar_searcher").typed.stop();
`
To stop it?

**Comment by Orlandster98** [comment]
@riverofjanuary you can see it on my [fork](https://github.com/Orlandster98/typed.js/tree/add-stop-function)

Just scroll down to the stop/start part.

**Comment by mattboldt** [comment]
Being added to https://github.com/mattboldt/typed.js/pull/264

**Pull request closed without merging**
