### PR TITLE
Improve typing

### PR DESCRIPTION
**Pull request by nitemarket**
When strings have same characters at the beginning of sentence, it will
not re-write. For example:
['I will love you', 'I will hate you', I still love you']
- 1st to 2nd: 'I will ' will remain
- 2nd to 3rd: 'I ' will remain

### CODE REVIEW

**Comment by fooness** [comment]
I’d love to have this feature. Unfortunately it doesn’t work for me with just setting stopNum, like the author wrote in his README.

Your code unfortunately break if there’s a delay in the string, like "^1000". Maybe HTML codes also won’t work anymore.

Can you imagine a fix for this?

**Comment by fooness** [comment]
Thank you, @nitemarket … I just wondered, it would be great to have an option for setting a delay after backspacing, before starting to type again …

https://github.com/mattboldt/typed.js/issues/167

**Comment by nitemarket** [comment]
@fooness Just added an option - restartDelay. Use it to delay after every backspacing ends

**Comment by fooness** [comment]
@nitemarket Thank you very much!

**Comment by zeel** [comment]
@fooness can we merge this PR? it would be great to have restartDelay option.

**Comment by fooness** [comment]
Please do so. But all gratitude goes to @nitemarket for his commits. : )

**Comment by mattboldt** [comment]
This is added on 2.0 https://github.com/mattboldt/typed.js/pull/264

**Pull request closed without merging**
