### PR TITLE
Created onTypingPaused and onTypingResumed callbacks + Added stringsTag option

### PR DESCRIPTION
**Pull request by Martin-Nyaga**
I added the capability to have callback functions that fire when the typing is paused using `^1000` (for example). 

I found this to be useful if you want to play a sound while typing. I was playing a keyboard sound while typing, and it needed to pause when the typing paused, and resume when the typing resumed.

The callbacks are added in the same way the `preStringTyped` and `onStringTyped` callbacks are added. as in the example in the index.htm file.

``` javascript

    $("#example").typed({
    // other config options
    // ...
        onTypingPaused: function(){
            // calllback here
            // same way for onTypingResumed
        }
     });
```

### CODE REVIEW

**Comment by ukkpower** [comment]
I have update my code to `console.log` these new callbacks as I want to add some sound as text types. However the callbacks are not fired so I don't get anything in the console. The typed.js is updated.

Any thoughts what I may have missed? Thanks

    $(function(){
        $(".terminal-animate").typed({
            strings: ["Hello my name is Earl, what is your name?\n"],
            typeSpeed: 20,
            backDelay: 500,
            loop: false,
            loopCount: false,
            onTypingPaused: function(){
                // calllback here
                // same way for onTypingResumed
                console.log("Paused")
            },
            onTypingResumed: function(){
                // calllback here
                // same way for onTypingResumed
                console.log("Resumed")
            }
        });
    });

**Comment by Martin-Nyaga** [comment]
Hi Keith,

These callbacks fire when you pause manually using "^". So if you add, for
example, ^2000 in your string, they will fire.

The preStringTyped and onStringTyped callbacks handle the
in-between-strings cases.

It should work if you add a manual pause.

Cheers,
Martin

I have update my code to console.log these new callbacks as I want to add
some sound as text types. However the callbacks are not fired so I don't
get anything in the console. The typed.js is updated.

Any thoughts what I may have missed? Thanks

$(function(){
    $(".terminal-animate").typed({
        strings: ["Hello my name is Earl, what is your name?\n"],
        typeSpeed: 20,
        backDelay: 500,
        loop: false,
        loopCount: false,
        onTypingPaused: function(){
            // calllback here
            // same way for onTypingResumed
            console.log("Paused")
        },
        onTypingResumed: function(){
            // calllback here
            // same way for onTypingResumed
            console.log("Resumed")
        }
    });
});

—
Reply to this email directly or view it on GitHub
<https://github.com/mattboldt/typed.js/pull/141#issuecomment-196573034>.

**Comment by Martin-Nyaga** [comment]
I have added the option to choose what tag is selected as the source of strings from a `stringsElement`, in reference to issue #155.

For example if you have:

```html
<div id="stringsElement">
    <span>Hello World</span>
    <span>I am another string</span>
</div>
```

Then your javascript would be:

```javascript
$("#typed").typed({
    stringsElement: $('#stringsElement'),
    stringsTag: 'span'
});
```

It also defaults to `'p'` when no tag is present, as was the case earlier.

**Comment by iamchriswick** [comment]
Your latest example here does not work for me... Have you updated the bower version?

**Comment by mattboldt** [comment]
Leaving this open to add to https://github.com/mattboldt/typed.js/pull/264

**Pull request closed without merging**
