### PR TITLE
Fix HTML element movement caused by empty tag

### PR DESCRIPTION
**Pull request by g4b1nagy**
When typed.js goes from one sentence to the other,
it first does an .empty() on the DOM node,
after which it proceeds to write the sentence
one character at a time.

At .empty(), the corresponding HTML element's
height becomes 0, which in some cases
causes the elements below it to jump up.
When the first character is inserted into
the HTML, the height becomes non-zero again
which causes the elements below to move down.

By replacing .empty() with .html('\&nbsp;'),
we ensure that the element's height never
goes down to 0.

### CODE REVIEW

**Comment by g4b1nagy** [comment]
PS: thank you for sharing the script with us, Matt :)

**Comment by kylejburt** [comment]
I think I am having the same problem here. Did you change this in the script itself or in the html placement of the content?

**Comment by g4b1nagy** [comment]
Library got updated in the meantime.

**Comment by RafaElZgz** [comment]
5 years have passed and I am still facing on how to deal with this problem without using css

**Pull request closed without merging**
